
/* Drop Tables */

DROP TABLE IF EXISTS MEMBER;




/* Create Tables */

-- 用户表
CREATE TABLE MEMBER
(
	ID BIGSERIAL NOT NULL,
	-- 用户名
	USERNAME VARCHAR(32) NOT NULL UNIQUE,
	-- 密码
	PASSWORD VARCHAR(32) NOT NULL,
	-- Email
	EMAIL VARCHAR(256),
	PRIMARY KEY (ID)
) WITHOUT OIDS;



/* Comments */

COMMENT ON TABLE MEMBER IS '用户表';
COMMENT ON COLUMN MEMBER.USERNAME IS '用户名';
COMMENT ON COLUMN MEMBER.PASSWORD IS '密码';
COMMENT ON COLUMN MEMBER.EMAIL IS 'Email';



